// AUTO-GENERATED by scripts/build.js — do not edit
// Statically imports every tool so esbuild can bundle them all.

const tool0 = require('../tools/agile/create-agile-board');
const tool1 = require('../tools/agile/create-sprint');
const tool2 = require('../tools/agile/get-agile-board');
const tool3 = require('../tools/agile/get-agile-boards');
const tool4 = require('../tools/agile/get-sprint');
const tool5 = require('../tools/agile/get-sprints');
const tool6 = require('../tools/agile/update-agile-board');
const tool7 = require('../tools/agile/update-sprint');
const tool8 = require('../tools/articles/add-article-comment');
const tool9 = require('../tools/articles/create-article');
const tool10 = require('../tools/articles/delete-article-comment');
const tool11 = require('../tools/articles/delete-article');
const tool12 = require('../tools/articles/get-article-attachments');
const tool13 = require('../tools/articles/get-article-comments');
const tool14 = require('../tools/articles/get-article');
const tool15 = require('../tools/articles/get-sub-articles');
const tool16 = require('../tools/articles/search-articles');
const tool17 = require('../tools/articles/update-article-comment');
const tool18 = require('../tools/articles/update-article');
const tool19 = require('../tools/commands/apply-command');
const tool20 = require('../tools/commands/get-command-suggestions');
const tool21 = require('../tools/issue-link-types/create-issue-link-type');
const tool22 = require('../tools/issue-link-types/get-issue-link-types');
const tool23 = require('../tools/issue-link-types/update-issue-link-type');
const tool24 = require('../tools/issues/add-comment-reaction');
const tool25 = require('../tools/issues/add-issue-comment');
const tool26 = require('../tools/issues/change-issue-assignee');
const tool27 = require('../tools/issues/create-issue');
const tool28 = require('../tools/issues/delete-comment-reaction');
const tool29 = require('../tools/issues/delete-issue-attachment');
const tool30 = require('../tools/issues/delete-issue-comment');
const tool31 = require('../tools/issues/delete-issue-link');
const tool32 = require('../tools/issues/delete-issue');
const tool33 = require('../tools/issues/delete-work-item');
const tool34 = require('../tools/issues/get-issue-activities');
const tool35 = require('../tools/issues/get-issue-attachments');
const tool36 = require('../tools/issues/get-issue-comments');
const tool37 = require('../tools/issues/get-issue-count');
const tool38 = require('../tools/issues/get-issue-links');
const tool39 = require('../tools/issues/get-issue-vcs-changes');
const tool40 = require('../tools/issues/get-issue-work-items');
const tool41 = require('../tools/issues/get-issue');
const tool42 = require('../tools/issues/link-issues');
const tool43 = require('../tools/issues/log-work');
const tool44 = require('../tools/issues/manage-issue-tags');
const tool45 = require('../tools/issues/move-issue-to-project');
const tool46 = require('../tools/issues/search-issues');
const tool47 = require('../tools/issues/update-issue-comment');
const tool48 = require('../tools/issues/update-issue');
const tool49 = require('../tools/issues/update-work-item');
const tool50 = require('../tools/issues/upload-issue-attachment');
const tool51 = require('../tools/projects/create-project');
const tool52 = require('../tools/projects/find-projects');
const tool53 = require('../tools/projects/get-issue-fields-schema');
const tool54 = require('../tools/projects/get-project');
const tool55 = require('../tools/saved-queries/create-saved-query');
const tool56 = require('../tools/saved-queries/delete-saved-query');
const tool57 = require('../tools/saved-queries/get-saved-issue-searches');
const tool58 = require('../tools/saved-queries/update-saved-query');
const tool59 = require('../tools/tags/create-tag');
const tool60 = require('../tools/tags/delete-tag');
const tool61 = require('../tools/tags/get-tags');
const tool62 = require('../tools/tags/update-tag');
const tool63 = require('../tools/users/find-user-groups');
const tool64 = require('../tools/users/find-user');
const tool65 = require('../tools/users/get-current-user');
const tool66 = require('../tools/users/get-user-group-members');
const tool67 = require('../tools/users/get-user-profile');
const tool68 = require('../tools/users/get-users');
const tool69 = require('../tools/work-items/get-all-work-items');

export interface AiTool {
  name: string;
  description: string;
  inputSchema: object;
  annotations?: object;
  outputSchema?: object;
  execute: (ctx: any) => any;
}

export const ALL_TOOLS: AiTool[] = [
  ...(tool0.aiTool ? [tool0.aiTool as AiTool] : []),
  ...(tool1.aiTool ? [tool1.aiTool as AiTool] : []),
  ...(tool2.aiTool ? [tool2.aiTool as AiTool] : []),
  ...(tool3.aiTool ? [tool3.aiTool as AiTool] : []),
  ...(tool4.aiTool ? [tool4.aiTool as AiTool] : []),
  ...(tool5.aiTool ? [tool5.aiTool as AiTool] : []),
  ...(tool6.aiTool ? [tool6.aiTool as AiTool] : []),
  ...(tool7.aiTool ? [tool7.aiTool as AiTool] : []),
  ...(tool8.aiTool ? [tool8.aiTool as AiTool] : []),
  ...(tool9.aiTool ? [tool9.aiTool as AiTool] : []),
  ...(tool10.aiTool ? [tool10.aiTool as AiTool] : []),
  ...(tool11.aiTool ? [tool11.aiTool as AiTool] : []),
  ...(tool12.aiTool ? [tool12.aiTool as AiTool] : []),
  ...(tool13.aiTool ? [tool13.aiTool as AiTool] : []),
  ...(tool14.aiTool ? [tool14.aiTool as AiTool] : []),
  ...(tool15.aiTool ? [tool15.aiTool as AiTool] : []),
  ...(tool16.aiTool ? [tool16.aiTool as AiTool] : []),
  ...(tool17.aiTool ? [tool17.aiTool as AiTool] : []),
  ...(tool18.aiTool ? [tool18.aiTool as AiTool] : []),
  ...(tool19.aiTool ? [tool19.aiTool as AiTool] : []),
  ...(tool20.aiTool ? [tool20.aiTool as AiTool] : []),
  ...(tool21.aiTool ? [tool21.aiTool as AiTool] : []),
  ...(tool22.aiTool ? [tool22.aiTool as AiTool] : []),
  ...(tool23.aiTool ? [tool23.aiTool as AiTool] : []),
  ...(tool24.aiTool ? [tool24.aiTool as AiTool] : []),
  ...(tool25.aiTool ? [tool25.aiTool as AiTool] : []),
  ...(tool26.aiTool ? [tool26.aiTool as AiTool] : []),
  ...(tool27.aiTool ? [tool27.aiTool as AiTool] : []),
  ...(tool28.aiTool ? [tool28.aiTool as AiTool] : []),
  ...(tool29.aiTool ? [tool29.aiTool as AiTool] : []),
  ...(tool30.aiTool ? [tool30.aiTool as AiTool] : []),
  ...(tool31.aiTool ? [tool31.aiTool as AiTool] : []),
  ...(tool32.aiTool ? [tool32.aiTool as AiTool] : []),
  ...(tool33.aiTool ? [tool33.aiTool as AiTool] : []),
  ...(tool34.aiTool ? [tool34.aiTool as AiTool] : []),
  ...(tool35.aiTool ? [tool35.aiTool as AiTool] : []),
  ...(tool36.aiTool ? [tool36.aiTool as AiTool] : []),
  ...(tool37.aiTool ? [tool37.aiTool as AiTool] : []),
  ...(tool38.aiTool ? [tool38.aiTool as AiTool] : []),
  ...(tool39.aiTool ? [tool39.aiTool as AiTool] : []),
  ...(tool40.aiTool ? [tool40.aiTool as AiTool] : []),
  ...(tool41.aiTool ? [tool41.aiTool as AiTool] : []),
  ...(tool42.aiTool ? [tool42.aiTool as AiTool] : []),
  ...(tool43.aiTool ? [tool43.aiTool as AiTool] : []),
  ...(tool44.aiTool ? [tool44.aiTool as AiTool] : []),
  ...(tool45.aiTool ? [tool45.aiTool as AiTool] : []),
  ...(tool46.aiTool ? [tool46.aiTool as AiTool] : []),
  ...(tool47.aiTool ? [tool47.aiTool as AiTool] : []),
  ...(tool48.aiTool ? [tool48.aiTool as AiTool] : []),
  ...(tool49.aiTool ? [tool49.aiTool as AiTool] : []),
  ...(tool50.aiTool ? [tool50.aiTool as AiTool] : []),
  ...(tool51.aiTool ? [tool51.aiTool as AiTool] : []),
  ...(tool52.aiTool ? [tool52.aiTool as AiTool] : []),
  ...(tool53.aiTool ? [tool53.aiTool as AiTool] : []),
  ...(tool54.aiTool ? [tool54.aiTool as AiTool] : []),
  ...(tool55.aiTool ? [tool55.aiTool as AiTool] : []),
  ...(tool56.aiTool ? [tool56.aiTool as AiTool] : []),
  ...(tool57.aiTool ? [tool57.aiTool as AiTool] : []),
  ...(tool58.aiTool ? [tool58.aiTool as AiTool] : []),
  ...(tool59.aiTool ? [tool59.aiTool as AiTool] : []),
  ...(tool60.aiTool ? [tool60.aiTool as AiTool] : []),
  ...(tool61.aiTool ? [tool61.aiTool as AiTool] : []),
  ...(tool62.aiTool ? [tool62.aiTool as AiTool] : []),
  ...(tool63.aiTool ? [tool63.aiTool as AiTool] : []),
  ...(tool64.aiTool ? [tool64.aiTool as AiTool] : []),
  ...(tool65.aiTool ? [tool65.aiTool as AiTool] : []),
  ...(tool66.aiTool ? [tool66.aiTool as AiTool] : []),
  ...(tool67.aiTool ? [tool67.aiTool as AiTool] : []),
  ...(tool68.aiTool ? [tool68.aiTool as AiTool] : []),
  ...(tool69.aiTool ? [tool69.aiTool as AiTool] : []),
];
