const esbuild = require('esbuild');
const path = require('path');
const fs = require('fs');
const { glob } = require('glob');

async function build() {
  // Sort to keep tools-registry.ts deterministic across machines / OSes —
  // glob's default order is filesystem-dependent and pollutes diffs.
  const toolFiles = (await glob('src/tools/**/*.ts')).sort();

  // ── npm MCP Server build ─────────────────────────────────────────────────
  // 1. Auto-generate src/server/tools-registry.ts with static imports for all tools.
  //    This lets esbuild bundle every tool into dist/server/index.js with the
  //    Node.js-compatible shims replacing the YouTrack runtime modules.

  const registryLines = [
    '// AUTO-GENERATED by scripts/build.js — do not edit',
    '// Statically imports every tool so esbuild can bundle them all.',
    '',
  ];

  const toolImports = [];
  for (let i = 0; i < toolFiles.length; i++) {
    const normPath = toolFiles[i].split(path.sep).join('/');
    // relative import path from src/server/ to src/tools/…
    const relImport = normPath.replace(/^src\//, '../').replace(/\.ts$/, '');
    const varName = `tool${i}`;
    registryLines.push(`const ${varName} = require('${relImport}');`);
    toolImports.push(varName);
  }

  registryLines.push('');
  registryLines.push('export interface AiTool {');
  registryLines.push('  name: string;');
  registryLines.push('  description: string;');
  registryLines.push('  inputSchema: object;');
  registryLines.push('  annotations?: object;');
  registryLines.push('  outputSchema?: object;');
  registryLines.push('  execute: (ctx: any) => any;');
  registryLines.push('}');
  registryLines.push('');
  registryLines.push('export const ALL_TOOLS: AiTool[] = [');
  for (const v of toolImports) {
    registryLines.push(`  ...(${v}.aiTool ? [${v}.aiTool as AiTool] : []),`);
  }
  registryLines.push('];');
  registryLines.push('');

  const registryPath = path.join('src', 'server', 'tools-registry.ts');
  fs.writeFileSync(registryPath, registryLines.join('\n'));
  console.log(`Generated: ${registryPath} (${toolImports.length} tools)`);

  // 2. Bundle the server entry + all tools into a single dist/server/index.js
  if (!fs.existsSync('dist/server')) {
    fs.mkdirSync('dist/server', { recursive: true });
  }

  esbuild.buildSync({
    entryPoints: ['src/server/index.ts'],
    bundle: true,
    platform: 'node',
    target: 'node18',
    format: 'cjs',
    outfile: 'dist/server/index.js',
    // Replace YouTrack runtime modules with Node.js-compatible shims
    alias: {
      '@jetbrains/youtrack-scripting-api/http': path.resolve('src/lib/http-node.ts'),
      '@jetbrains/youtrack-scripting-api/entities': path.resolve('src/lib/entities-node.ts'),
      '@jetbrains/youtrack-scripting-api/app': path.resolve('src/lib/app-node.ts'),
    },
    // Keep the MCP SDK as external — it ships with the npm package and resolves at runtime
    external: ['@modelcontextprotocol/sdk'],
    minify: false,
  });

  console.log('Built: dist/server/index.js');
}

build().catch(err => {
  console.error(err);
  process.exit(1);
});